DATAFRAMES

Creating a DataFrame

In [26]:
import numpy as np
import pandas as pd

In [27]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and Indexing of columns

In [29]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [30]:
df2[["Name"]]

    Name
0   John
1   Anna
2  Peter
3  Linda

In [31]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

Creating a new column

In [32]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Engg."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000       Engg.

Removing Column

In [33]:
df2.drop('Designation',axis =1 )

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [34]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000       Engg.

In [35]:
df2.drop('Designation',axis =1 , inplace=True)

In [36]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [37]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

AXIS=0 For ROW 


AXIS=1 For Column


We can also remove multiple columns and rows use list.


If we want to remove column or row from main DB permanently use (inplace=True).

Selecting Rows

In [38]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [39]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [43]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [41]:
df2.loc[[0]]

   Name  Age      City  Salary
0  John   28  New York   65000

In [46]:
df.iloc[[3]]

    Name  Age    City  Salary
3  Linda   42  London   85000

For Access Rows 

loc keyword-Location/Name of row

iloc keyword-Index of row

Selecting Subsets of Rows and Columns

In [47]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [51]:
df.iloc[[1,2]][["City","Salary"]]

     City  Salary
1   Paris   70000
2  Berlin   62000

Conditional Selection

In [52]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [53]:
#I only want to see those people whose age is above 30

In [55]:
df2["Age"] > 30

0    False
1     True
2    False
3     True
Name: Age, dtype: bool

In [56]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [57]:
#I only want people whose age is above 30 and their city must be paris

In [66]:
df2[(df2["Age"] > 30) & (df2['City'] == 'Paris' )]

   Name  Age   City  Salary
1  Anna   34  Paris   70000